exclude_paths:
  - collections
  - .pre-commit-config.yaml
  - roles/oddish/templates/dendrite-config-default.yml
skip_list:
  - fqcn[action-core]
  - var-naming[no-role-prefix]
  - name[casing]
  - no-handler
enable_list:
  - empty-string-compare
  - jinja-template-extension
  - no-log-password
  - no-same-owner
offline: true
