[project]
name = "ansible-homelab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12" # should match .pre-commit-config.yaml
dependencies = [
    "ansible",
    "ansible-core<2.20", # should match .pre-commit-config.yaml
    "ansible-lint>=26.6.0",
    "clustershell>=1.10.1",
    "pre-commit>=4.6.1",
]
