groups:
  - name: custom_alerts
    rules:
      - alert: "systemd ExecMainStatus != 0"
        expr: systemd_unit_exec_main_status != 0
        labels:
          severity: warning
        annotations:
          summary: "systemd service crashed! (ExecMainStatus == {{ $value }})"
          description: "systemd service crashed! (ExecMainStatus == {{ $value }})"
      - alert: "systemd Result != 'success'"
        expr: systemd_unit_result_success != 1
        labels:
          severity: warning
        annotations:
          summary: "systemd service crashed! (Result != 'success')"
          description: "systemd service crashed! (Result != 'success')"
