- name: systemctl daemon-reload
  systemd_service:
    daemon_reload: true

- name: systemctl --user -M simon@ daemon-reload
  command: systemctl --user -M simon@ daemon-reload
  changed_when: true

- name: systemctl --user -M hookshot@ daemon-reload
  command: systemctl --user -M hookshot@ daemon-reload
  changed_when: true

- name: systemctl --user -M synapse@ daemon-reload
  command: systemctl --user -M synapse@ daemon-reload
  changed_when: true

- name: systemctl --user -M podman@ daemon-reload
  command: systemctl --user -M podman@ daemon-reload
  changed_when: true

- name: systemctl --user -M prometheus@ daemon-reload
  command: systemctl --user -M prometheus@ daemon-reload
  changed_when: true

- name: systemctl restart gitea
  systemd_service:
    name: gitea
    state: restarted

- name: systemctl reload apache2
  systemd_service:
    name: apache2
    state: reloaded

- name: systemctl restart node_exporter
  systemd_service:
    name: node_exporter
    state: restarted

- name: sudo -u simon podman system migrate
  command: podman system migrate
  changed_when: true
  become: true
  become_user: simon

- name: sudo -u hookshot podman system migrate
  command: podman system migrate
  changed_when: true
  become: true
  become_user: hookshot

- name: sudo -u synapse podman system migrate
  command: podman system migrate
  changed_when: true
  become: true
  become_user: synapse

- name: sudo -u prometheus podman system migrate
  command: podman system migrate
  changed_when: true
  become: true
  become_user: prometheus

- name: systemctl --user -M simon@ restart hello
  command: systemctl --user -M simon@ restart hello
  changed_when: true

- name: systemctl --user -M simon@ restart hello2
  command: systemctl --user -M simon@ restart hello2
  changed_when: true

- name: systemctl --user -M prometheus@ restart prometheus
  command: systemctl --user -M prometheus@ restart prometheus
  changed_when: true

- name: systemctl --user -M synapse@ restart matrix-synapse
  command: systemctl --user -M synapse@ restart matrix-synapse
  changed_when: true

- name: systemctl --user -M hookshot@ restart matrix-hookshot
  command: systemctl --user -M hookshot@ restart matrix-hookshot
  changed_when: true
