- name: setup subvolid=5 btrfs mounts for each drive
  vars:
    devices:
      - nvme0n1p2
      - sda1
      - TODO
  block:
    - name: setup directory
      file:
        path: "/mnt/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      loop: "{{ devices }}"
    - name: setup mount
      ansible.posix.mount:
        src: "/dev/{{ item }}"
        path: "/mnt/{{ item }}"
        fstype: btrfs
        state: mounted
        opts: defaults,subvolid=5
      loop: "{{ devices }}"

- name: check mounts
  command: mount
  changed_when: false
  check_mode: false
  register: mount

# if the @home subvolume did not exist yet, creating it and migrating all the files from /home
# is not something that I want to implement via ansible
# this should be done manually at OS installation time
# see README.md
- name: assert that expected btrfs subvolumes have been mounted
  fail:
    msg: "one or more expected btrfs subvolumes are not mounted: {{ mounts_missing | to_json }}"
  vars:
    subvolumes:
      "@": /
      "@home": /home
      "@swap": /swap
      "@snapshots": /.snapshots
    nvme_btrfs_mounts: "{{ mount.stdout | community.general.jc('mount') | selectattr('type', 'equalto', 'btrfs') | selectattr('filesystem', 'equalto', '/dev/nvme0n1p2') }}"
    mounts_missing: |-
      {%- set output = [] -%}
      {%- for subvol, mount_point in subvolumes.items() -%}
      {%- if nvme_btrfs_mounts | selectattr('mount_point', 'equalto', mount_point) | selectattr('options', 'contains', 'subvol=/' + subvol) | length == 0 -%}
      {%- set _ = output.append([subvol, mount_point]) -%}
      {%- endif -%}
      {%- endfor -%}
      {{ output }}
  when: mounts_missing | length > 0

- name: install /etc/btrbk.conf
  copy:
    content: |
      snapshot_dir /.snapshots
      snapshot_preserve_min latest
      snapshot_preserve 1h 1d 1w
      subvolume /
      subvolume /home
    dest: /etc/btrbk.conf
    owner: root
    group: root
    mode: "0644"

- name: update systemd timer to be hourly instead of daily
  copy:
    content: |
      [Unit]
      Description=btrbk hourly timer

      [Timer]
      OnCalendar=*-*-* *:00:00
    dest: /etc/systemd/system/btrbk.timer.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: systemctl daemon-reload
