# NOTE: manual btrfs setup is required at OS installation time, see README.md

- name: setup subvolumes
  vars:
    subvolumes:
      - name: "@snapshots"
        path: "/.snapshots"
  block:
    - name: create subvolumes
      community.general.btrfs_subvolume:
        name: "{{ item.name }}"
        filesystem_device: /dev/nvme0n1p2
        automount: true
      loop: "{{ subvolumes }}"
    - name: mount subvolumes
      ansible.posix.mount:
        src: /dev/nvme0n1p2
        path: "{{ item.path }}"
        fstype: btrfs
        state: mounted
        opts: "defaults,subvol={{ item.name }}"
      loop: "{{ subvolumes }}"

- name: install /etc/btrbk.conf
  copy:
    content: |
      snapshot_dir /.snapshots
      snapshot_preserve_min 1h
      snapshot_preserve 1h 1d 1w
      subvolume /
      subvolume /home
    dest: /etc/btrbk.conf
    owner: root
    group: root
    mode: "0644"

- name: update systemd timer to be hourly instead of daily
  copy:
    content: |
      [Unit]
      Description=btrbk hourly timer

      [Timer]
      OnCalendar=*-*-* *:00:00
    dest: /etc/systemd/system/btrbk.timer.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: systemctl daemon-reload
