- name: git group
  group:
    name: git
    system: true

- name: git user
  user:
    name: git
    home: /home/git
    password_lock: true
    group: git
    comment: Git Version Control
    shell: /bin/bash
    system: true
    state: present

- name: install gitea
  get_url:
    url: https://dl.gitea.com/gitea/1.27.0/gitea-1.27.0-linux-amd64
    dest: /usr/local/bin/gitea
    owner: root
    group: root
    mode: "0755"
    checksum: sha256:3b190a162b90e3c94317b3354fca6c1fedd6fe1476e45088368f2ade97a0b01d
    force: false
  notify: systemctl restart gitea

- name: create gitea directories
  unity.file_multi_diff.file:
    path: "{{ item }}"
    state: directory
    owner: git
    group: git
    mode: "0750"
  loop:
    - /etc/gitea
    - /var/lib/gitea
    - /var/lib/gitea/custom
    - /var/lib/gitea/data
    - /var/lib/gitea/log

- name: install /etc/gitea/app.ini
  unity.template_multi_diff.template:
    src: gitea-app.ini.j2
    dest: /etc/gitea/app.ini
    owner: git
    group: git
    mode: "0600"
  notify: systemctl restart gitea

- name: install gitea systemd service unit file
  unity.copy_multi_diff.copy:
    src: gitea.service
    dest: /etc/systemd/system/gitea.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemctl daemon-reload
    - systemctl restart gitea

- name: systemctl enable gitea
  systemd_service:
    name: gitea
    enabled: true
