# NOTE: podman-related hookshot tasks are in tasks/podman.yml, not tasks/hookshot.yml

- name: create the hookshot group
  ansible.builtin.group:
    name: hookshot
    system: true
    state: present

- name: create the hookshot user account
  ansible.builtin.user:
    name: hookshot
    group: hookshot
    shell: /usr/sbin/nologin
    system: true
    create_home: true
    state: present

- name: setup /etc/matrix-hookshot/
  unity.file_multi_diff.file:
    path: /etc/matrix-hookshot
    state: directory
    owner: hookshot
    group: hookshot
    mode: "0755"

- name: install /etc/matrix-hookshot/registration.yml
  unity.template_multi_diff.template:
    src: matrix-hookshot-registration.yml.j2
    dest: /etc/matrix-hookshot/registration.yml
    owner: hookshot
    group: hookshot
    mode: "0644"
  notify:
    - systemctl --user -M hookshot@ restart matrix-hookshot
    - systemctl --user -M synapse@ restart matrix-synapse

- name: install /etc/matrix-hookshot/config.yml
  unity.template_multi_diff.template:
    src: matrix-hookshot-config.yml.j2
    dest: /etc/matrix-hookshot/config.yml
    owner: hookshot
    group: hookshot
    mode: "0644"
  notify: systemctl --user -M hookshot@ restart matrix-hookshot

- name: install /etc/matrix-hookshot/passkey.pem
  unity.copy_multi_diff.copy:
    src: matrix-hookshot-passkey.pem
    dest: /etc/matrix-hookshot/passkey.pem
    owner: hookshot
    group: hookshot
    mode: "0640"
  notify: systemctl --user -M hookshot@ restart matrix-hookshot

- name: install /etc/matrix-hookshot/format-prometheus.js
  copy:
    src: matrix-hookshot-format-prometheus.js
    dest: /etc/matrix-hookshot/format-prometheus.js
    owner: hookshot
    group: hookshot
    mode: "0644"

- name: install matrix hookshot JS transform helper script
  copy:
    content: |
      #!/bin/bash
      if [ -z "$TOKEN" ]; then
          echo "error: must set TOKEN environment variable"
          exit 1
      fi
      if [ $# != 3 ]; then
          echo "error: must provide room ID (including '!'), hook name, and .js file path as arguments"
          exit 1
      fi
      FUNCTION="$(<$3)"
      if grep -q '"' <<<"$FUNCTION"; then
          echo "error: .js file cannot contain double quotes"
          exit 1
      fi
      if [ "$(wc -l <<<"$FUNCTION")" != 1 ]; then
          echo "error: .js file cannot contain newlines"
          exit 1
      fi
      echo "$TOKEN" | curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer $(</dev/stdin)" 'http://127.0.0.1:8008/_matrix/client/v3/rooms/'"$1"'/state/uk.half-shot.matrix-hookshot.generic.hook/'"$2" -d '{"name":"alertmanager","transformationFunction":"'"$FUNCTION"'"}'
      echo
    dest: /usr/local/bin/matrix-hookshot-apply-transformation-js.bash
    owner: hookshot
    group: hookshot
    mode: "0755"
