- name: setup secrets
  include_vars: secrets.yml
  tags: [always]

- name: set timezone
  community.general.timezone:
    name: America/New_York

- name: certbot
  import_tasks: certbot.yml
  tags: [certbot]

- name: DDNS
  unity.copy_multi_diff.copy:
    content: |
      */5 * * * * root echo url="https://www.duckdns.org/update?domains={{ duckdns_domain }}&token={{ duckdns_token }}" | curl -k -o /var/log/ddns.log -K -
    dest: /etc/cron.d/duckdns
    owner: root
    group: root
    mode: "0600"

- name: gitea
  import_tasks: gitea.yml
  tags: [gitea]
