- name: minecraft group
  group:
    name: minecraft
    system: true

- name: minecraft user
  user:
    name: minecraft
    home: /home/minecraft
    password_lock: true
    group: minecraft
    comment: minecraft
    shell: /bin/bash
    system: true
    state: present

- name: apt install JRE
  apt:
    name: default-jre-headless
    state: present
  notify: systemctl restart minecraft-matt

- name: setup directories
  file:
    path: "{{ item }}"
    state: directory
    owner: minecraft
    group: minecraft
    mode: "0755"
  loop:
    - /opt/minecraft
    - /opt/minecraft/aio-mc-rcon
    - /opt/minecraft/matt
    - /opt/minecraft/matt/mods

- name: install server.jar
  get_url:
    url: "https://meta.fabricmc.net/v2/versions/loader/26.2/0.19.5/1.1.2/server/jar"
    dest: /opt/minecraft/matt/fabric_server_26.2_0.19.5_1.1.2.jar
    owner: minecraft
    group: minecraft
    mode: "0644"

- name: symlink server.jar
  file:
    path: /opt/minecraft/matt/server.jar
    src: /opt/minecraft/matt/fabric_server_26.2_0.19.5_1.1.2.jar
    state: link
  notify: systemctl restart minecraft-matt

- name: install mods
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: minecraft
    group: minecraft
    mode: "0644"
  loop:
    - url: "https://cdn.modrinth.com/data/P7dR8mSH/versions/UWwhUX3k/fabric-api-0.160.0%2B26.2.jar"
      dest: /opt/minecraft/matt/mods/fabric-api-0.160.0+26.2.jar
    - url: "https://cdn.modrinth.com/data/rd9rKuJT/versions/8bBHJTea/disconnect-packet-fix-fabric-2.2.0.jar"
      dest: /opt/minecraft/matt/mods/disconnect-packet-fix-fabric-2.2.0.jar
  notify: systemctl restart minecraft-matt

- name: install server.properties
  template:
    src: server.properties.j2
    dest: /opt/minecraft/matt/server.properties
    owner: minecraft
    group: minecraft
    mode: "0600"
  notify: systemctl restart minecraft-matt

- name: install rcon_password file
  copy:
    dest: /opt/minecraft/matt/rcon_password
    content: |
      {{ minecraft_matt_rcon_password }}
    owner: minecraft
    group: minecraft
    mode: "0600"

- name: install aio-mc-rcon
  pip:
    name: aio-mc-rcon
    state: present
    virtualenv: /opt/minecraft/aio-mc-rcon/venv
  become: true
  become_user: minecraft

- name: install mc-rcon wrapper script
  copy:
    dest: /usr/local/bin/mc-rcon
    src: mc-rcon.py
    owner: minecraft
    group: minecraft
    mode: "0750"

- name: install mc-stop wrapper script
  copy:
    src: mc-stop.bash
    dest: /usr/local/bin/mc-stop
    owner: minecraft
    group: minecraft
    mode: "0750"

- name: install minecraft-matt.service
  copy:
    src: minecraft-matt.service
    dest: /etc/systemd/system/minecraft-matt.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemctl daemon-reload
    - systemctl restart minecraft-matt

- name: systemctl enable minecraft-matt.service
  systemd_service:
    name: minecraft-matt
    enabled: true
