- name: minecraft group
  group:
    name: minecraft
    system: true

- name: minecraft user
  user:
    name: minecraft
    home: /home/minecraft
    password_lock: true
    group: minecraft
    comment: minecraft
    shell: /bin/bash
    system: true
    state: present

- name: apt install JRE
  apt:
    name: default-jre-headless
    state: present
  notify: systemctl restart minecraft-matt

- name: setup directories
  file:
    path: "{{ item }}"
    state: directory
    owner: minecraft
    group: minecraft
    mode: "0755"
  loop:
    - /opt/minecraft
    - /opt/minecraft/aio-mc-rcon
    - /opt/minecraft/matt

# TODO install server_26.2.jar

- name: symlink server.jar
  file:
    path: /opt/minecraft/matt/server.jar
    src: /opt/minecraft/matt/server_26.2.jar
    state: link
  notify: systemctl restart minecraft-matt

- name: install server.properties
  template:
    src: server.properties.j2
    dest: /opt/minecraft/matt/server.properties
    owner: minecraft
    group: minecraft
    mode: "0600"
  notify: systemctl restart minecraft-matt

- name: install rcon_password file
  copy:
    dest: /opt/minecraft/matt/rcon_password
    content: |
      {{ minecraft_matt_rcon_password }}
    owner: minecraft
    group: minecraft
    mode: "0600"

- name: install aio-mc-rcon
  pip:
    name: aio-mc-rcon
    state: present
    virtualenv: /opt/minecraft/aio-mc-rcon/venv
  become: true
  become_user: minecraft

- name: install mc-rcon wrapper script
  copy:
    dest: /usr/local/bin/mc-rcon
    src: mc-rcon.py
    owner: minecraft
    group: minecraft
    mode: "0750"

- name: install mc-stop wrapper script
  copy:
    src: mc-stop.bash
    dest: /usr/local/bin/mc-stop
    owner: minecraft
    group: minecraft
    mode: "0750"

- name: install minecraft-matt.service
  copy:
    src: minecraft-matt.service
    dest: /etc/systemd/system/minecraft-matt.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemctl daemon-reload
    - systemctl restart minecraft-matt

- name: systemctl enable minecraft-matt.service
  systemd_service:
    name: minecraft-matt
    enabled: true
