- name: minecraft group
  group:
    name: minecraft
    system: true

- name: minecraft user
  user:
    name: minecraft
    home: /home/minecraft
    password_lock: true
    group: minecraft
    comment: minecraft
    shell: /bin/bash
    system: true
    state: present

- name: apt install JRE
  apt:
    name: default-jre-headless
    state: present
  notify: systemctl restart minecraft-matt

- name: setup directories
  file:
    path: "{{ item }}"
    state: directory
    owner: minecraft
    group: minecraft
    mode: "0755"
  loop:
    - /opt/minecraft
    - /opt/minecraft/aio-mc-rcon
    - /opt/minecraft/matt

# TODO install server_26.2.jar

- name: symlink server.jar
  file:
    path: /opt/minecraft/matt/server.jar
    src: /opt/minecraft/matt/server_26.2.jar
    state: link
  notify: systemctl restart minecraft-matt

- name: install server.properties
  template:
    src: server.properties.j2
    dest: /opt/minecraft/matt/server.properties
    owner: minecraft
    group: minecraft
    mode: "0600"
  notify: systemctl restart minecraft-matt

- name: install rcon_password file
  copy:
    dest: /opt/minecraft/matt/rcon_password
    content: |
      {{ minecraft_matt_rcon_password }}
    owner: minecraft
    group: minecraft
    mode: "0600"

- name: install aio-mc-rcon
  pip:
    name: aio-mc-rcon
    state: present
    virtualenv: /opt/minecraft/aio-mc-rcon/venv
  become: true
  become_user: minecraft

- name: install mc-rcon wrapper script
  copy:
    dest: /usr/local/bin/mc-rcon
    content: |
      #!/opt/minecraft/aio-mc-rcon/venv/bin/python
      import sys, asyncio
      from aiomcrcon import Client
      async def main():
          assert not sys.stdin.isatty()
          password = sys.stdin.read().strip()
          assert len(sys.argv) == 2
          command = sys.argv[1]
          async with Client("127.0.0.1", 25575, password) as client:
              response = await client.send_cmd(command)
              print(response)
      if __name__ == "__main__":
          asyncio.run(main())
    owner: minecraft
    group: minecraft
    mode: "0750"

- name: install mc-stop wrapper script
  copy:
    dest: /usr/local/bin/mc-stop
    content: |
      #!/bin/bash
      set -euo pipefail
      trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
      # Note that it is usually not sufficient to specify a command for this setting that only asks the service to terminate (for example, by sending some form of termination signal to it), but does not wait for it to do so.
      # Since the remaining processes of the services are killed according to KillMode= and KillSignal= or RestartKillSignal= as described above immediately after the command exited, this may not result in a clean stop.
      # The specified command should hence be a synchronous operation, not an asynchronous one.
      # Also note that the stop operation is always performed if the service started successfully, even if the processes in the service terminated on their own or were killed.
      # The stop commands must be prepared to deal with that case.
      # https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html
      if ! nc -zv 127.0.0.1 25575 &>/dev/null; then
          echo "server is not running?"
          exit 0
      fi
      /usr/local/bin/mc-rcon stop </opt/minecraft/matt/rcon_password
      elapsed=0
      while [ "$elapsed" -lt 30 ] && nc -zv 127.0.0.1 25575 &>/dev/null; do
          echo "waiting for server to stop ($elapsed)..."
          elapsed=$((elapsed + 1))
          sleep 1
      done
    owner: minecraft
    group: minecraft
    mode: "0750"

- name: install minecraft-matt.service
  copy:
    content: |
      [Unit]
      Description=minecraft server - matt
      [Service]
      User=minecraft
      Group=minecraft
      WorkingDirectory=/opt/minecraft/matt
      ExecStart=java -jar ./server.jar
      Restart=on-failure
      ExecStop=/usr/local/bin/mc-stop
      SuccessExitStatus=0 1
      ProtectHome=true
      ProtectSystem=full
      PrivateDevices=true
      NoNewPrivileges=true
      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/minecraft-matt.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemctl daemon-reload
    - systemctl restart minecraft-matt

- name: systemctl enable minecraft-matt.service
  systemd_service:
    name: minecraft-matt
    enabled: true
