- name: systemctl enable wpa_supplicant
  systemd_service:
    name: wpa_supplicant
    enabled: true

- name: update netplan config
  unity.template_multi_diff.template:
    src: netplan.yml.j2
    dest: /etc/netplan/00-installer-config.yaml
    owner: root
    group: root
    mode: "0600"
  register: netplan_config

- name: systemctl restart wpa_supplicant
  systemd_service:
    name: wpa_supplicant
    state: restarted
  when: netplan_config.changed

- name: netplan try && netplan apply
  shell: netplan try && netplan apply
  changed_when: true
  when: netplan_config.changed

# the default unit file includes two commands in series:
# ExecStart=/lib/systemd/systemd-networkd-wait-online -i wlp2s0:degraded enp1s0f0:degraded
# ExecStart=/lib/systemd/systemd-networkd-wait-online --any --dns -o routable -i wlp2s0 -i enp1s0f0
# it waits for both ifaces to reach a degraded state before then waiting for either iface to come up fully
# it blocks boot and it doesn't make sense to me, so I removed the first one
- name: install override for systemd-networkd-wait-online
  copy:
    content: |
      [Service]
      ExecStart=
      ExecStart=/lib/systemd/systemd-networkd-wait-online --any --dns -o routable -i wlp2s0 -i enp1s0f0
    dest: /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: systemctl daemon-reload
