- name: overwrite /etc/subuid, /etc/subgid
  unity.copy_multi_diff.copy:
    content: |
      {% for podman_container in podman_containers %}
      {{ podman_container.user }}:{{ 1000000 + 100000 * loop.index0 }}:65536
      {% endfor %}
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - /etc/subuid
    - /etc/subgid
  notify: "{{ podman_containers | map(attribute='user') | map('regex_replace', '^(.*)$', 'sudo -u \\1 podman system migrate') }}"

- name: getent passwd
  getent: { database: passwd }

- name: setup user-specific systemd containers directory
  unity.file_multi_diff.file:
    path: "/etc/containers/systemd/users/{{ uid_number }}"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0755"
  loop: "{{ podman_containers }}"
  vars:
    uid_number: "{{ getent_passwd[item.user][1] }}"

- name: install container unit file
  unity.template_multi_diff.template:
    src: "{{ item.name }}.container.j2"
    dest: "/etc/containers/systemd/users/{{ uid_number }}/{{ item.name }}.container"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0644"
  loop: "{{ podman_containers }}"
  vars:
    uid_number: "{{ getent_passwd[item.user][1] }}"
    uidmap:
      - "0:0:1"
      - "1:{{ 1 + 65536 * item.index }}:65535"
    gidmap:
      - "0:0:1"
      - "1:{{ 1 + 65536 * item.index }}:65535"
  notify: |
    {% set output = [] %}
    {% for podman_container in podman_containers %}
    {% set _ = output.append('systemctl --user -M ' ~ podman_container.user ~ '@ daemon-reload') %}
    {% set _ = output.append('systemctl --user -M ' ~ podman_container.user ~ '@ restart ' ~ podman_container.name) %}
    {% endfor %}
    {{ output }}

- name: loginctl enable-linger
  ansible.builtin.command:
    cmd: loginctl enable-linger "{{ item.user }}"
    creates: "/var/lib/systemd/linger/{{ item.user }}"
  loop: "{{ podman_containers }}"
