- name: overwrite /etc/subuid, /etc/subgid
  unity.copy_multi_diff.copy:
    content: |
      {% for podman_container in podman_containers %}
      {{ podman_container.user }}:{{ 1000000 + 100000 * loop.index0 }}:65536
      {% endfor %}
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - /etc/subuid
    - /etc/subgid
  notify: "{{ podman_containers | map(attribute='user') | map('regex_replace', '^(.*)$', 'sudo -u \\1 podman system migrate') }}"

- name: getent passwd
  getent:
    database: passwd

- name: setup user-specific systemd containers directory
  unity.file_multi_diff.file:
    path: "/etc/containers/systemd/users/{{ getent_passwd[item.user][1] }}"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0755"
  loop: "{{ podman_containers }}"

- name: copy quadlet unit file
  unity.copy_multi_diff.copy:
    src: "{{ item.name }}.container"
    dest: "/etc/containers/systemd/users/{{ getent_passwd[item.user][1] }}/{{ item.name }}.container"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ podman_containers }}"
  notify: |
    {% set output = [] %}
    {% for podman_container in podman_containers %}
    {% set _ = output.append('systemctl --user -M ' ~ podman_container.user ~ '@ daemon-reload') %}
    {% set _ = output.append('systemctl --user -M ' ~ podman_container.user ~ '@ restart ' ~ podman_container.name) %}
    {% endfor %}
    {{ output }}
