- name: overwrite /etc/subuid, /etc/subgid
  unity.copy_multi_diff.copy:
    content: |
      {% for podman_container in podman_containers %}
      {{ podman_container.user }}:{{ 1000000 + 100000 * loop.index0 }}:65536
      {% endfor %}
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - /etc/subuid
    - /etc/subgid
  notify: "{{ podman_containers | map(attribute='user') | map('regex_replace', '^(.*)$', 'sudo -u \\1 podman system migrate') }}"

- name: getent passwd
  getent: { database: passwd }

- name: setup user-specific systemd containers directory
  unity.file_multi_diff.file:
    path: "/etc/containers/systemd/users/{{ uid_number }}"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0755"
  loop: "{{ podman_containers }}"
  vars:
    uid_number: "{{ getent_passwd[item.user][1] }}"

- name: install container unit file
  unity.template_multi_diff.template:
    src: "{{ item.name }}.container.j2"
    dest: "/etc/containers/systemd/users/{{ uid_number }}/{{ item.name }}.container"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0644"
  loop: "{{ podman_containers }}"
  loop_control:
    extended: true
  vars:
    uid_number: "{{ getent_passwd[item.user][1] }}"
    # podman rootless UID mapping is tricky
    # https://docs.podman.io/en/latest/markdown/podman-run.1.html#uidmap-flags-container-uid-from-uid-amount
    # podman automatically builds its uid_map based on /etc/subuid before the --uidmap argument takes effect
    # the --uidmap argument maps container UIDs to the "intermediate UIDs" that were created in this implicit uid_map
    # and then intermediate UIDs are mapped to real UIDs
    # implicit uid_map example:
    # 0 -> real UID of whoever called the `podman` command
    # 1-63356 -> 1000000-10065535 (1st range in /etc/subuid)
    # 65537-131072 -> 2000000-20063355 (2nd range in /etc/subuid)
    # note: to show this implicit uid_map: `podman unshare cat /proc/self/uid_map`
    # note: make sure to `podman system migrate` after making any changes to /etc/subuid
    uidmap:
      - "0:0:1"
      - "1:{{ 1 + 65536 * item.index }}:65535"
    gidmap:
      - "0:0:1"
      - "1:{{ 1 + 65536 * item.index }}:65535"
  notify: |
    {% set output = [] %}
    {% for podman_container in podman_containers %}
    {% set _ = output.append('systemctl --user -M ' ~ podman_container.user ~ '@ daemon-reload') %}
    {% set _ = output.append('systemctl --user -M ' ~ podman_container.user ~ '@ restart ' ~ podman_container.name) %}
    {% endfor %}
    {{ output }}

- name: loginctl enable-linger
  ansible.builtin.command:
    cmd: loginctl enable-linger "{{ item.user }}"
    creates: "/var/lib/systemd/linger/{{ item.user }}"
  loop: "{{ podman_containers }}"
