- name: prometheus group
  group:
    name: prometheus
    system: true

- name: prometheus user (parity with `simon-prometheus` user on BNKR-NAS)
  user:
    name: prometheus
    home: /home/prometheus
    password_lock: true
    group: prometheus
    groups: ["{{ bnkr_nas_simon_shared_folder_access_group_gid_number }}"]
    comment: prometheus
    shell: /bin/bash
    system: true
    uid: "{{ bnkr_nas_simon_prometheus_user_uid_number }}"
    state: present

- name: setup /etc/prometheus/
  unity.file_multi_diff.file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"

- name: install /etc/prometheus/prometheus.yml
  unity.template_multi_diff.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: "0644"
  notify: systemctl --user -M prometheus@ restart prometheus

- name: install /etc/prometheus/node_exporter_alerts.yml
  get_url:
    url: https://gist.githubusercontent.com/krisek/62a98e2645af5dce169a7b506e999cd8/raw/b67dd1dad1bcf2896f56dd02a657d8eac8e893ea/alert.rules.yml
    dest: /etc/prometheus/node_exporter_alerts.yml
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: setup /var/lib/prometheus/
  unity.file_multi_diff.file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0750"
  notify: systemctl --user -M prometheus@ restart prometheus
