- name: Add Tailscale stable APT repository
  deb822_repository:
    name: tailscale-stable
    types: [deb]
    uris: "https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}"
    signed_by: "https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.asc"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [main]
    state: present
    enabled: true
  register: apt_source_tailscale

- name: apt update
  apt: { update_cache: true }
  when: apt_source_tailscale.changed

- name: apt install tailscale
  apt:
    name: tailscale
    state: present
  notify: systemctl restart tailscaled
# NOTE: despite that the tailscaled systemd service will be up and running at this point
# you still have to run `tailscale up` and follow the link and authenticate in browser
# to join a tailnet
